### ISSUE TITLE
Pass through DOSBox config params

### ISSUE THREAD

**Issue by BreadYogurt** [dreamer/steam-dos#11]
I want to use my own render settings for all games but I don't see a way to do that aside from editing each game's config manually.

**Comment by dreamer** [comment]
You mean settings, that usually go into `[render]` section in dosbox conf file?

You can place them in file `steam_dos_<appid>_<id>.conf`, which is being created on start in game's installation dir. Except sometimes it might be hard to find, because some games use working directories deeper into installation dir.

Perhaps I should make it a bit clearer in README file… or add empty section in that file…

BTW, I am reworking how this file is generated - when version 0.3.1 will be released, user settings will be overwritten (once, I have no other choice to make fullscreen work properly). You can test it (and enjoy fullscreen working with multi-screen setups) on branch `next`. I plan to release 0.3.1 later this week.

**Comment by BreadYogurt** [comment]
Yeah, it would be good to have some options in `steam-dos.conf` so that I don't have to insert them into every game's individual config file.

**Comment by dreamer** [comment]
OK, just released version 0.3.1 - it defaults to scaler `normal3x` for all games (which can be changed by user in settings file) and imports `render.aspect` from publishers' conf files to `[render]` section of game-specific conf file.

@BreadYogurt do you think this is enough, or are you missing some options?

**Comment by dreamer** [comment]
I am closing this issue for now, as there's no clear issue to be fixed here any more. Feel free to reopen.
